export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const RECEIVE_SINGLE_PRODUCT = 'RECEIVE_SINGLE_PRODUCT';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const RECEIVE_SINGLE_CATEGORY= 'RECEIVE_SINGLE_CATEGORY';
export const SET_SEARCH = 'SET_SEARCH';
export const ADD_CART = 'ADD_CART';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const CHECKOUT_CART = "CHECKOUT_CART";
