export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const RECEIVE_SINGLE_PRODUCT = 'RECEIVE_SINGLE_PRODUCT';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const SET_SEARCH = 'SET_SEARCH';
export const ADD_CART = 'ADD_CART';